### ISSUE TITLE
Install pyahocorasick to allow the use of --word-list flag

### ISSUE THREAD

**Issue by belaaiza** [lirantal/docker-detect-secrets#4]
The [Yelp's detect-secrets tool allow the use of --word-list ](https://github.com/Yelp/detect-secrets#wordlist) flag to pass a file with words to be ignored, but this flag requires the installation of `pyahocorasick`, which could be done by:
```
pip install detect-secrets[word_list]
```
My suggestion is to replace the [current pip install ](https://github.com/lirantal/docker-detect-secrets/blob/master/Dockerfile#L15) with the one above, allowing people to use the `--word-list` flag.

**Comment by belaaiza** [comment]
@lirantal if you agree with this I have made a [PR](https://github.com/lirantal/docker-detect-secrets/pull/5), but as `pyahocorasick` is implemented in C, I needed to install `build-essential` too, what caused the image to increase in size by 161MB (the first one is the new image):

<img width="804" alt="Captura de Tela 2021-06-15 às 17 15 25" src="https://user-images.githubusercontent.com/14032043/122117484-4a2fd200-cdfd-11eb-8dd8-e2a901b30b48.png">

**Comment by lirantal** [comment]
Yep, that sounds a great enhancement.
