### ISSUE TITLE
Specifying a specific version of detect-secrets

### ISSUE THREAD

**Issue by tokidoki11** [lirantal/docker-detect-secrets#8]
Thanks for the great work,

I saw this package and want to utilize this
https://hub.docker.com/r/lirantal/detect-secrets/tags

As I can see in the docker hub, the available tag is `latest` `main` and `nightly`

It will be super if version could be specified

**Comment by lirantal** [comment]
Thanks.

You mean to specify the version of the `detect-secrets` npm package, or something else...? helpful if you can be more elaboraate.

**Comment by tokidoki11** [comment]
@lirantal detect-secrets version

as in their released version https://github.com/Yelp/detect-secrets/releases
currently it is version 1.4.0

usually docker image comes with tag of their version of main item inside
https://hub.docker.com/_/node

**Comment by tokidoki11** [comment]
my suggestion is maybe for now
create a tag of 1.4.0 from latest

and if somehow detect-secrets got updated you can create a new tag of the version and update the latest tag as well

**Comment by lirantal** [comment]
I'll get to this tomorrow I hope!

**Comment by lirantal** [comment]
I've re-enabled the GitHub actions workflow which run on a scheduled cron to push images both to GCR as well as Docker Hub. This means it'll build a new image version and push it.

There won't be a specific tag but the latest will now use the latest of detect-secrets too.
